source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'devise'
gem 'hydra-head'

gem 'hydra-collections', :path=>'../../'
gem 'rspec-rails'
gem 'factory_girl'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-rails'
  gem 'uglifier', '>= 1.0.3'
end
